# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:latest

pipelines:
  default:
    - step:
        image: perl:5.26
        caches:
          - perl
          - cpan
        script:
          - cpan -T "local::lib"
          - eval "$(perl -Mlocal::lib=${PWD}/perl_modules)"   # set local lib to ./perl_modules
          - cpan -T "MediaWiki::API"
          - perl -MMediaWiki::API -e 'my $mw = MediaWiki::API->new()'
definitions:
  caches:
    perl: perl_modules
    cpan: /root/.cpan




      
      
      
      

      
      


